# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
    - --preserve-quotes
    - --indent=2
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.32.2
  hooks:
  - id: markdownlint
    args:
    - --fix
    verbose: true
    entry: bash -c 'markdownlint "$@" || true' --

